services:
  db:
    image: postgres:15.10
    environment:
      - POSTGRES_DB=bookdb
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
