[project]
name = "ninja-version"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12.6"
dependencies = [
    "django-ninja>=1.4.1",
    "psycopg2-binary>=2.9.0",
    "uvicorn>=0.35.0",
]
