# Generated by Django 5.2.1 on 2025-05-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('page', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
